### ISSUE TITLE
Oboznámiť sa s témou

### ISSUE THREAD

**Issue by KillianSvk** [TIS2024-FMFI/ml-intro#1]
odkaz: [odkaz](https://youtu.be/XJ7HLz9VYz0?si=qiG7xnGtXjJOj9fV)

**Comment by kuboo1** [comment]
[Odkaz 2: ](https://www.youtube.com/watch?v=ntKn5TPHHAk&themeRefresh=1)

**Comment by BushDemon** [comment]
Naštudované

**Comment by KillianSvk** [comment]
Pozreté

**Comment by pavelpetrovic** [comment]
inspiracia
https://fb.watch/vwrqiJ-heP/
