### ISSUE TITLE
Vytvoriť katalóg požiadaviek

### ISSUE THREAD

**Issue by KillianSvk** [TIS2024-FMFI/ml-intro#3]
Vytvoriť do Wiki katalóg požiadaviek

**Comment by pavelpetrovic** [comment]
mojich zopar komentarov ku KP, nalozte s nimi ako uznate za vhodne:

 - pismo velkost 11 alebo 12
 - zarovnavat na oba okraje
 - netreba sa privelmi rozpisovat, skor je podstatny obsah
 - poziadavky v casti 3 musia byt jasne oznacene (cisla, pismena...)
 - prosim o novu iteraciu, ktora bude konkretnejsie opisovat funkcionalitu aplikacie.

**Comment by BushDemon** [comment]
Opravil som velkost písma a zarovnanie
