### ISSUE TITLE
Vytvoriť návrh používateľského rozhrania

### ISSUE THREAD

**Issue by KillianSvk** [TIS2024-FMFI/ml-intro#8]
nakreslené a popísané všetky dialógy, okná a stránky, ktorými aplikácia komunikuje s používateľom

**Comment by BushDemon** [comment]
Pridal som do navrhu dva scenare z navrhu pouzivatelskeho rozhrania a component diagram

**Comment by KillianSvk** [comment]
treba sa dohodnut so zadavatelom ako ma vyzerat 3. scenar
